name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    name: Check for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        working-directory: ./movie-ui
        run: npm install

      - name: Authenticate with Snyk
        run: npx snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Test
        working-directory: ./movie-ui
        run: npx snyk test
